package com.single.model.dto.chat;

import java.util.Date;

public class ChatRoomDTO {

	private int CHATROOM_CHIEF_CODE;
	private int CHATROOM_CODE;
	private int CHATROOM_VERIFY;
	private String CHATROOM_TITLE;
	private Date CHATROOM_CREATEDATE;
	private int CHATROOM_MEMBER_COUNT;

	private int MEMBER_CODE;
	private String MEMBER_NICKNAME;

	public ChatRoomDTO() {
	}

	public ChatRoomDTO(int cHATROOM_CHIEF_CODE, int cHATROOM_CODE, int cHATROOM_VERIFY, String cHATROOM_TITLE,
			Date cHATROOM_CREATEDATE, int cHATROOM_MEMBER_COUNT, int mEMBER_CODE, String mEMBER_NICKNAME) {
		CHATROOM_CHIEF_CODE = cHATROOM_CHIEF_CODE;
		CHATROOM_CODE = cHATROOM_CODE;
		CHATROOM_VERIFY = cHATROOM_VERIFY;
		CHATROOM_TITLE = cHATROOM_TITLE;
		CHATROOM_CREATEDATE = cHATROOM_CREATEDATE;
		CHATROOM_MEMBER_COUNT = cHATROOM_MEMBER_COUNT;
		MEMBER_CODE = mEMBER_CODE;
		MEMBER_NICKNAME = mEMBER_NICKNAME;
	}

	@Override
	public String toString() {
		return "ChatRoomDTO [CHATROOM_CHIEF_CODE=" + CHATROOM_CHIEF_CODE + ", CHATROOM_CODE=" + CHATROOM_CODE
				+ ", CHATROOM_VERIFY=" + CHATROOM_VERIFY + ", CHATROOM_TITLE=" + CHATROOM_TITLE
				+ ", CHATROOM_CREATEDATE=" + CHATROOM_CREATEDATE + ", CHATROOM_MEMBER_COUNT=" + CHATROOM_MEMBER_COUNT
				+ ", MEMBER_CODE=" + MEMBER_CODE + ", MEMBER_NICKNAME=" + MEMBER_NICKNAME + "]";
	}

	public int getCHATROOM_CHIEF_CODE() {
		return CHATROOM_CHIEF_CODE;
	}

	public void setCHATROOM_CHIEF_CODE(int cHATROOM_CHIEF_CODE) {
		CHATROOM_CHIEF_CODE = cHATROOM_CHIEF_CODE;
	}

	public int getCHATROOM_CODE() {
		return CHATROOM_CODE;
	}

	public void setCHATROOM_CODE(int cHATROOM_CODE) {
		CHATROOM_CODE = cHATROOM_CODE;
	}

	public int getCHATROOM_VERIFY() {
		return CHATROOM_VERIFY;
	}

	public void setCHATROOM_VERIFY(int cHATROOM_VERIFY) {
		CHATROOM_VERIFY = cHATROOM_VERIFY;
	}

	public String getCHATROOM_TITLE() {
		return CHATROOM_TITLE;
	}

	public void setCHATROOM_TITLE(String cHATROOM_TITLE) {
		CHATROOM_TITLE = cHATROOM_TITLE;
	}

	public Date getCHATROOM_CREATEDATE() {
		return CHATROOM_CREATEDATE;
	}

	public void setCHATROOM_CREATEDATE(Date cHATROOM_CREATEDATE) {
		CHATROOM_CREATEDATE = cHATROOM_CREATEDATE;
	}

	public int getCHATROOM_MEMBER_COUNT() {
		return CHATROOM_MEMBER_COUNT;
	}

	public void setCHATROOM_MEMBER_COUNT(int cHATROOM_MEMBER_COUNT) {
		CHATROOM_MEMBER_COUNT = cHATROOM_MEMBER_COUNT;
	}

	public int getMEMBER_CODE() {
		return MEMBER_CODE;
	}

	public void setMEMBER_CODE(int mEMBER_CODE) {
		MEMBER_CODE = mEMBER_CODE;
	}

	public String getMEMBER_NICKNAME() {
		return MEMBER_NICKNAME;
	}

	public void setMEMBER_NICKNAME(String mEMBER_NICKNAME) {
		MEMBER_NICKNAME = mEMBER_NICKNAME;
	}

}
