package com.single.model.dto.chat;

import java.util.Date;

public class ChatMessageDTO {

	private int CHATROOM_CODE;
	private int CHATMESSAGE_CODE;
	private String CHATMESSAGE_CONTENT;
	private Date CHATMESSAGE_SENDDATE;

	private int CHATMESSAGE_FROM;
	private String MEMBER_NICKNAME;
	private String MPROFILE_IMG_SERVERNAME;

	public ChatMessageDTO() {
	}

	public ChatMessageDTO(int cHATROOM_CODE, int cHATMESSAGE_CODE, String cHATMESSAGE_CONTENT,
			Date cHATMESSAGE_SENDDATE, int cHATMESSAGE_FROM, String mEMBER_NICKNAME, String mPROFILE_IMG_SERVERNAME) {
		CHATROOM_CODE = cHATROOM_CODE;
		CHATMESSAGE_CODE = cHATMESSAGE_CODE;
		CHATMESSAGE_CONTENT = cHATMESSAGE_CONTENT;
		CHATMESSAGE_SENDDATE = cHATMESSAGE_SENDDATE;
		CHATMESSAGE_FROM = cHATMESSAGE_FROM;
		MEMBER_NICKNAME = mEMBER_NICKNAME;
		MPROFILE_IMG_SERVERNAME = mPROFILE_IMG_SERVERNAME;
	}

	@Override
	public String toString() {
		return "ChatMessageDTO [CHATROOM_CODE=" + CHATROOM_CODE + ", CHATMESSAGE_CODE=" + CHATMESSAGE_CODE
				+ ", CHATMESSAGE_CONTENT=" + CHATMESSAGE_CONTENT + ", CHATMESSAGE_SENDDATE=" + CHATMESSAGE_SENDDATE
				+ ", CHATMESSAGE_FROM=" + CHATMESSAGE_FROM + ", MEMBER_NICKNAME=" + MEMBER_NICKNAME
				+ ", MPROFILE_IMG_SERVERNAME=" + MPROFILE_IMG_SERVERNAME + "]";
	}

	public int getCHATROOM_CODE() {
		return CHATROOM_CODE;
	}

	public void setCHATROOM_CODE(int cHATROOM_CODE) {
		CHATROOM_CODE = cHATROOM_CODE;
	}

	public int getCHATMESSAGE_CODE() {
		return CHATMESSAGE_CODE;
	}

	public void setCHATMESSAGE_CODE(int cHATMESSAGE_CODE) {
		CHATMESSAGE_CODE = cHATMESSAGE_CODE;
	}

	public String getCHATMESSAGE_CONTENT() {
		return CHATMESSAGE_CONTENT;
	}

	public void setCHATMESSAGE_CONTENT(String cHATMESSAGE_CONTENT) {
		CHATMESSAGE_CONTENT = cHATMESSAGE_CONTENT;
	}

	public Date getCHATMESSAGE_SENDDATE() {
		return CHATMESSAGE_SENDDATE;
	}

	public void setCHATMESSAGE_SENDDATE(Date cHATMESSAGE_SENDDATE) {
		CHATMESSAGE_SENDDATE = cHATMESSAGE_SENDDATE;
	}

	public int getCHATMESSAGE_FROM() {
		return CHATMESSAGE_FROM;
	}

	public void setCHATMESSAGE_FROM(int cHATMESSAGE_FROM) {
		CHATMESSAGE_FROM = cHATMESSAGE_FROM;
	}

	public String getMEMBER_NICKNAME() {
		return MEMBER_NICKNAME;
	}

	public void setMEMBER_NICKNAME(String mEMBER_NICKNAME) {
		MEMBER_NICKNAME = mEMBER_NICKNAME;
	}

	public String getMPROFILE_IMG_SERVERNAME() {
		return MPROFILE_IMG_SERVERNAME;
	}

	public void setMPROFILE_IMG_SERVERNAME(String mPROFILE_IMG_SERVERNAME) {
		MPROFILE_IMG_SERVERNAME = mPROFILE_IMG_SERVERNAME;
	}
}
